#pragma once
#define IOCTL_READ_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_WRITE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_GET_PID_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_GET_MODULE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


NTSTATUS IOCTLControl(PDEVICE_OBJECT DeviceObject, PIRP IRP);
NTSTATUS IOCTLCreate(PDEVICE_OBJECT DeviceObject, PIRP IRP);
NTSTATUS IOCTLClose(PDEVICE_OBJECT DeviceObject, PIRP IRP);